### ISSUE TITLE
Can I replicate the same with any public api? can u help me with it ??

### ISSUE THREAD

**Issue by Sruthi1498** [xidhu/FoodHunt#7]

**Comment by xidhu** [comment]
Yes there are a lot of identical public apis
      1.Test api endpoints with postman.
      2.change the get request part of application according to the format.

eg:
 <pre>
`{
    "data": {
        "success": true,
        "data": [
            {
                "id": "1",
                "name": "Pind Tadka",
                "rating": "4.1",
                "cost_for_one": "280",
                "image_url": "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
            },
            {
                "id": "2",
                "name": "Garbar Burgers",
                "rating": "4.6",
                "cost_for_one": "200",
                "image_url": "https://images.pexels.com/photos/1639565/pexels-photo-1639565.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
            },
        ]
    }
}`
</pre>
![Group 1](https://user-images.githubusercontent.com/64782756/122718052-13890a00-d28a-11eb-9a3f-e6d0a8c37a58.png)




But, to use Authentication services u need to build a custom server or integrate firebase Auth.
