### ISSUE TITLE
What is the API you used here ? and how u do register and login. what is this URL "http://13.235.250.119/v2/register/fetch_result"

### ISSUE THREAD

**Issue by Sruthi1498** [xidhu/FoodHunt#8]

**Comment by xidhu** [comment]
Oh...actually idk ...😃
i took it from a random github repo.
that's why i told that don't share any personal info to it.
so please don't use that if u can..make custom api or use firebase,It'll be more safe.

**Comment by Sruthi1498** [comment]
How to make a custom api instead of this ??

**Comment by xidhu** [comment]
Well ,u can build api using node.js or django or any other frameworks with what language u knw
its not a big deal.
I recommand u to use firebase,if u dont want to write server side code.

https://firebase.google.com/docs/reference
https://www.youtube.com/watch?v=4d-gIPGzmK4
https://firebase.google.com/docs/android/setup

**Comment by Sruthi1498** [comment]
I am creating a food ordering app. Can u help me with it... I face difficulty doing it...Can u help me please

**Comment by xidhu** [comment]
Ok... Mail me what exactly u want.. I will definitely help u if i can.. 👍

**Comment by Sruthi1498** [comment]
Ur mail id plz ?

**Comment by xidhu** [comment]
sidhu3612@gmail.com
